cors:
  originPatterns:
    - http://localhost:8080
    - http://localhost:3030
    
security:
  jwt:
    token:
      secret-key: 3333001
      expire-length: 3600000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_mordomo
    username: root
    password: 35828889
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

spring-doc:
  pathsToMatch: 
    - /api/**/v1/**
  swagger-ui:
    use-rooth-path: true
  